server:
  port: 16061

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      connection-timeout: 10000
      idleTimeout: 10000
      maximumPoolSize: 10
      minimumIdle: 5
      validation-timeout: 10000
    password: qwer1234
    url: jdbc:mariadb://localhost:23306/orderdb
    username: order
  rabbitmq:
    host: localhost
    password: qwer1234
    port: 5672
    username: jpetstore

feign:
  client:
    config: 
      catalog-api:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution.isolation.thread.timeoutInMilliseconds: 500
      circuitBreaker.errorThresholdPercentage: 50
      circuitBreaker.requestVolumeThreshold: 2
      metrics.rollingStats.timeInMilliseconds: 10000
      circuitBreaker.sleepWindowInMilliseconds: 5000

logging:
  level:
    com.netflix.hystrix: debug
    org.apache.http.impl: debug
    com.jpetstore.order: debug
    feign: debug

management:
  endpoint:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,env,metrics,refresh,bus-refresh

product.service.url: http://localhost:16062
